### ISSUE TITLE
Distinction of primary law vs implementing/delegated acts correct?

### ISSUE THREAD

**Issue by ChRauh** [michalovadek/eulaw#1]
Hi Michal,

Using the eurlex package for teaching currently (many thanks!) but stumbled across one issue on your EU output page in section 6 (Legal bases). Here you distinguish primary law from delegated/implementing acts along treaty base with the regex `str_detect(lbcelex, "^1.*([:digit:]|[:punct:])$")`.

The requirement to end on a digit or a punctuation character seems to filter out many Celex numbers that are actually treaty bases in my reading (random example: Euratom Celex "11957A").

Wouldn't it be simpler and more correct to just ask for Celex sector 1 ("Treaties") like `str_detect(lbcelex, "^1")`?

Best,
Christian

**Comment by michalovadek** [comment]
hi Christian, glad it's useful and thanks for bringing this up.

It used to be the case that EurLex would include among the legal bases of delegated and implementing acts the first line from the relevant part of the preamble (eg. HAVING REGARD TO THE TREATY ESTABLISHING THE EUROPEAN ECONOMIC COMMUNITY). These would be translated into Celex as eg 11957E. I did a quick search and it seems less common now, but you can see that this creates the impression that we are looking at a primary act (which we are not). Here is an example that at the time of writing this reply still contains a legal basis entry like that: https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:31969L0354

There are a few primary acts where the number is missing which get wrongly excluded as a result of the filtering, but this should be a relatively small number in the grand scheme of things. I try to keep a list of them for manual corrections / reporting to EurLex for fixing, so let me know if you see any

**Comment by ChRauh** [comment]
Thanks for the quick reply! Understood: your regex ensures that we are only considering cases in which a specific treaty article is provided as a legal base. 

I also see no systematic way to identify the possible remaining 'false negatives' (other than qualitatively digging into individual acts...).

Related side note: It took me a moment to understand that the query returns multiple observations (celex) once one includes additional metadata that contains multiple entries in the original database (such as legal basis, but also author etc.).
Perfectly logical but it may be useful to remind the uninitiated user of this behavior in the documentation (the description of elx_run_query might be the adequate spot in the reference manual).

In any case, many thanks for this resource!
